language: cpp
os: trusty
addons:
        apt:
                packages:
                        googletest
                        libgtest-dev
compiler: gcc
before_install: cd emulator&& sudo apt install libgtest-dev
